feature:
  - changed-files:
      - any-glob-to-any-file: ["**/*.go", "internal/**", "cmd/**"]
  - head-branch: ["^feature/"]

bugfix:
  - head-branch: ["^bugfix/", "^fix/"]

chore:
  - head-branch: ["^chore/", "^deps/"]
  - changed-files:
      - any-glob-to-any-file:
          [".github/**", "**/Dockerfile", "**/docker-compose*.yml"]

docs:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "docs/**"]

security:
  - changed-files:
      - any-glob-to-any-file:
          ["internal/**/crypto/**", "**/*auth*/*", "**/security/**"]

tests:
  - changed-files:
      - any-glob-to-any-file: ["**/*_test.go", "test/**"]
