extends: default

ignore: |
  .git/**
  LICENSES/**
  node_modules/**
  dist/**
  build/**
  coverage/**
  .reuse/**
  .github/ISSUE_TEMPLATE/**    # keep if you want to skip templates
  .github/PULL_REQUEST_TEMPLATE/**

rules:
  document-start: disable
  truthy: disable
  comments: disable
  comments-indentation: disable

  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: false

  line-length:
    max: 160
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  trailing-spaces: enable
  new-line-at-end-of-file: enable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0

  key-duplicates: enable
  colons: enable
  commas: enable
  hyphens: enable
  brackets: enable
  braces: enable
